import { ChangeEvent, useEffect, useState } from "react";
import { api } from "../api";
import type { Project, Run } from "../types";

export function ReportView({ project, run, notify }: { project: Project; run: Run | null; notify:(message:string,error?:boolean)=>void }) {
  const [report,setReport] = useState<any>(null); const [models,setModels]=useState<any[]>([]); const [modelId,setModelId]=useState(""); const [busy,setBusy]=useState(false); const [scoreJob,setScoreJob]=useState<any>(null);
  useEffect(()=>{
    setReport(null); setScoreJob(null);
    api.get<{models:any[]}>(`/projects/${project.id}/models`).then(value=>{setModels(value.models);setModelId(current=>current||value.models[0]?.id||"");}).catch(()=>undefined);
    if(run?.status==="succeeded") api.get(`/reports/${run.id}`).then(setReport).catch(error=>notify(error instanceof Error?error.message:"报告读取失败",true));
  },[project.id,run?.id,run?.status]);
  const score=async(event:ChangeEvent<HTMLInputElement>)=>{const file=event.target.files?.[0];if(!file||!modelId)return;setBusy(true);try{const form=new FormData();form.append("file",file);form.append("kind","score_input");const uploaded=await api.upload<any>(`/projects/${project.id}/data-assets`,form);const result=await api.post<any>("/score-jobs",{model_version_id:modelId,input_asset_id:uploaded.asset.id});setScoreJob(result.score_job);notify(`已为 ${result.score_job.rows.toLocaleString()} 条样本打分`);}catch(error){notify(error instanceof Error?error.message:"评分失败",true);}finally{setBusy(false);event.target.value="";}};
  if(!run||run.status!=="succeeded")return <div className="report-empty"><div className="stage-line"><div><span className="eyebrow">REPORT</span><h2>产物将在最终质检后生成</h2><p>Web、Excel、单文件 HTML 和模型包共享同一结构化报告数据。</p></div></div><div className="empty-state"><span>WAITING</span><p>{run?`当前 Run 状态：${run.status}`:"请选择或启动一个 Run。"}</p></div></div>;
  if(!report)return <div className="loading-panel">正在读取结构化模型报告…</div>;
  const summary=report.executive_summary||{};const champion=report.champion||{};
  return <div className="report-view"><div className="stage-line"><div><span className="eyebrow">RISK MODEL REPORT · {report.schema_version}</span><h2>{report.project.name} · {report.target.column}</h2><p>管理摘要与专业详情来自同一份事实数据。</p></div><div className="report-actions"><a className="button secondary" href={`/api/v1/reports/${run.id}/excel`}>导出 Excel</a><a className="button secondary" target="_blank" rel="noreferrer" href={`/api/v1/reports/${run.id}/html`}>打开单页 HTML</a></div></div>
    <div className="summary-grid five"><Metric label="Champion" value={summary.champion}/><Metric label="Test AUC" value={metric(summary.test_auc)}/><Metric label="Test KS" value={metric(summary.test_ks)}/><Metric label="OOT AUC" value={metric(summary.oot_auc)}/><Metric label="质检结论" value={summary.quality_verdict === "pass" ? "通过" : "条件通过"}/></div>
    {summary.quality_verdict !== "pass" && <div className="review-banner revise"><div><span>QUALITY NOTICE</span><strong>需关注排序</strong></div><p>{summary.quality_notes?.[0] || "Test 等频分箱未达到绝对排序。"}</p></div>}
    <section className="report-section"><div className="section-heading"><div><h3>Train / Test / OOT 整体效果</h3><p>样本量、好坏占比、AUC、KS、PR-AUC 与 PSI。</p></div></div><div className="table-wrap"><table><thead><tr><th>数据集</th><th>样本量</th><th>坏样本</th><th>坏占比</th><th>AUC</th><th>KS</th><th>PR-AUC</th><th>PSI</th></tr></thead><tbody>{Object.entries(report.sample_overview||{}).map(([name,value]:any)=><tr key={name}><td><strong>{name.toUpperCase()}</strong></td><td>{value.rows.toLocaleString()}</td><td>{value.positive_count.toLocaleString()}</td><td>{percent(value.bad_rate)}</td><td>{metric(champion[`${name}_metrics`]?.roc_auc)}</td><td>{metric(champion[`${name}_metrics`]?.ks)}</td><td>{metric(champion[`${name}_metrics`]?.pr_auc)}</td><td>{metric(name==="test"?champion.train_test_score_psi:name==="oot"?champion.test_oot_score_psi:null)}</td></tr>)}</tbody></table></div></section>
    <section className="report-section"><div className="section-heading"><div><h3>候选模型对比</h3><p>Test 选择，OOT 不参与候选排序。</p></div></div><div className="candidate-bars">{(report.model_comparison||[]).map((item:any)=><div key={item.candidate} className={item.candidate===summary.champion?"champion":""}><span>{item.candidate}</span><i style={{width:`${Math.max(0,Number(item.test_metrics?.roc_auc||0)*100)}%`}}/><b>{item.status==="trained"?`AUC ${metric(item.test_metrics?.roc_auc)} · KS ${metric(item.test_metrics?.ks)}`:item.error_code}</b></div>)}</div></section>
    <section className="report-section"><div className="section-heading"><div><h3>Champion 等频分箱</h3><p>坏占比、Lift、累计捕获与绝对排序。</p></div></div><div className="table-wrap"><table><thead><tr><th>数据集</th><th>箱</th><th>样本量</th><th>坏占比</th><th>Lift</th><th>累计捕获</th><th>坏概率区间</th></tr></thead><tbody>{Object.entries(champion.lift||{}).flatMap(([name,rows]:any)=>(rows||[]).map((row:any)=><tr key={`${name}-${row.bucket}`}><td>{name.toUpperCase()}</td><td>{row.bucket}</td><td>{row.count}</td><td>{percent(row.bad_rate)}</td><td>{metric(row.lift)}</td><td>{percent(row.cumulative_capture)}</td><td>{metric(row.min_probability)}—{metric(row.max_probability)}</td></tr>))}</tbody></table></div></section>
    <section className="report-section"><div className="section-heading"><div><h3>最终入模变量</h3><p>报告只展示最终入模变量；完整排除原因保留在 Run 证据中。</p></div><span className="count-badge">{report.feature_selection?.selected?.length||0}</span></div><div className="feature-pills">{(report.feature_selection?.selected||[]).map((item:any)=><span key={item.column}><b>{item.column}</b>IV {metric(item.iv)}</span>)}</div></section>
    <section className="score-panel"><div><span className="eyebrow">BATCH SCORING</span><h3>给新样本批量打分</h3><p>输出列使用模型名称命名，并同时保留原始分、坏概率与封顶/封底证据。</p></div><label>模型版本<select value={modelId} onChange={e=>setModelId(e.target.value)}>{models.map(model=><option value={model.id} key={model.id}>{model.name}</option>)}</select></label><label className={`button primary file-button ${busy||!modelId?"disabled":""}`}>{busy?"评分中…":"选择 CSV / Excel 并评分"}<input type="file" accept=".csv,.xlsx,.xlsm,.xls" disabled={busy||!modelId} onChange={score}/></label>{scoreJob&&<a className="button secondary" href={`/api/v1/score-jobs/${scoreJob.id}/download`}>下载 {scoreJob.rows.toLocaleString()} 行评分结果</a>}</section>
  </div>;
}

function Metric({label,value}:{label:string;value:any}){return <div className="summary-cell"><span>{label}</span><strong>{value??"—"}</strong></div>}
function metric(value:any){return value==null?"—":Number(value).toFixed(4)}
function percent(value:any){return value==null?"—":`${(Number(value)*100).toFixed(2)}%`}
